AllTheThings.lua

Using the global ToggleMiniListForCurrentZone was not opening the zone
minilist when ctrl+left clicking the minimap button, but replacing the
global function with the function in the app object was resolving this
problem.

Ctrl+Left: Use app.ToggleMiniListForCurrentZone

---

contrib/Parser/DATAS/02 - Outdoor Zones/03 Outland/Zangarmarsh/Quests.lua

Quest 'Strange Engine Part' in Zangarmash is repeatable.

Quest 'Strange Engine Part' in Zangarmash is repeatable.

---

AllTheThings.lua
contrib/Parser/DATAS/11 - Professions/Engineering/Recipes/Cataclysm Engineering - Filtered.lua
contrib/Parser/DATAS/11 - Professions/Engineering/Recipes/Engineering - Filtered.lua
contrib/Parser/DATAS/11 - Professions/Engineering/Recipes/Gnomish/Gnomish Engineering.lua
contrib/Parser/DATAS/11 - Professions/Engineering/Recipes/Goblin/Goblin Engineering.lua
contrib/Parser/DATAS/11 - Professions/Engineering/Recipes/Northrend Engineering - Filtered.lua
contrib/Parser/DATAS/11 - Professions/Engineering/Recipes/Outland Engineering - Filtered.lua
contrib/Parser/DATAS/11 - Professions/Engineering/Recipes/Pandaria Engineering - Filtered.lua
contrib/Parser/DATAS/11 - Professions/Engineering/Recipes/_ Automation.lua

I added filtering in profession recipes based on specialization, for BFA the only profession that still has exclusive recipes is engineering but it could be extended for Classic for Blacksmithing, Leatherworking, and Tailoring because I have not hardcoded the specializations, there is a table between professions and specializations.
For players who want to filter recipes without the account wide option enable currently the addon does not show recipes for not learned profession, from other classes or from other factions, so it makes sense that specializations work the same way and exclude recipes from the non-learned specialization.
What happens if the players have not learned any specialization? Exactly the same as what happens if the player has not learned any profession, the recipes do …

Engineering specialization recipe filter

---

contrib/Parser/DATAS/21 - Holidays/07 - Brewfest/Legacy.lua

Added legacy quests for old tankards
Did Someone Say "Souvenir?"  2007
Say, There Wouldn't Happen to be a Souvenir This Year, Would There?  2008
Another Year, Another Souvenir 2009-2010 Alliance version
I think all of this quest is marked as yearly in Blizzard database because I have the tankard from 2008 and 2009 but those quests were reset.
Also 
This One Time, When I Was Drunk... Daily Legacy

Brewfest Legacy Quests

---

contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/01 Darnassus/Vendors.lua

was pet id instead of formula id, showed up as like you can buy pet (even for non enchanters)

fix formula id

---

contrib/Parser/DATAS/21 - Holidays/09 - Hallow's End/Quests.lua

Also Northrend Dalaran Neutral and Alliance Candy Buckets had the wrong quest id
With this change Hollow End can be 100% completed by Horde characters, I am not sure about Alliance because I have not completed all candy bucket quests with an alliance character to check if some horde only quest is missing Horde Only mark

Missing ALLIANCE_ONLY in four Candy Bucket quests

---

contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Durotar/Quests.lua
contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Northern Barrens/Quests.lua
contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/Arathi Highlands/Quests.lua
contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/Hillsbrad Foothills/Quests.lua
contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/Northern Stranglethorn/Quests.lua
contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/Tirisfal Glades/Quests.lua

361 -- A Letter Undelivered (Legacy)
590 -- A Rogue's Deal (Legacy)
594 -- Message in a Bottle (Legacy)
615 -- The Captain's Cutlass (Legacy)
620 -- The Monogrammed Sash (Legacy)
635 -- Crystal in the Mountains (Legacy)
663 -- Land Ho! (Legacy)
665 -- Sunken Treasure (Legacy)
668 -- Sunken Treasure (Legacy)
669 -- Sunken Treasure (Legacy)
670 -- Sunken Treasure (Legacy)
676 -- The Hammer May Fall (Legacy)
830 -- The Admiral's Orders (Legacy)
831 -- The Admiral's Orders (Legacy)
832 -- Burning Shadows (Legacy)
883 -- Lakota'mani (Legacy)
885 -- Washte Pawne (Legacy)

Some more quests added for issue #398

---

AllTheThings.lua

Still some rendering caveats based on individual UI scale and screen size or whatever, but this seems to be pretty accurate for making the icons line up in the data windows

Fixed ATT icon alignment

---

.contrib/Parser/_main.lua
AllTheThings.lua

I did some debugging to try and find why the **/attwq** window lags so horribly during active faction invasions and made some tweaks to the logic as a result. _Also in main.lua, value2 was spelled valu2 so that would probably explode if it even was actually called, but it seems to be in a place where an error() would be thrown regardless and I couldn't think of anywhere it would actually be utilized._
It looks like the Rebuild() method is thrown onto the Stack for processing, but anytime an API call to retrieve the itemID or currencyID for a given existing world quest reward returned _nil_, the entire function would simply return true, causing the Stack to re-evaluate the entire method on the next pass of OnUpdate. This would then cause the iterative, stuttering of the entire game while …

ATT WorldQuests Modification

---

AllTheThings.lua

Some logic in the Quest lib was only treating repeatable Quests as collectible if the '**Only First Time**' setting was _additionally_ toggled with the '**Track Repeatable Things**' setting being enabled. This shouldn't be the case since the '**Only First Time**' setting is already functioning correctly to provide the _completion status_ of a Quest when it is treated as collectible and has been completed at least once.

Fixed 'Track Repeatable Quests'

---

AllTheThings.lua

Currently, the recursive expand/collapse logic is based on the **first** subgroup when clicking the header group of a window. This leads to the World Quests window (or any other window with a non-expandable first group row) being unable to be recursively collapsed by clicking the header row. Additionally, if the first subgroup was not expanded, but any other subgroups within the window were expanded, clicking the header group would simply expand all subgroups, requiring an additional click to collapse all subgroups.
This proposed change alters the logic slightly to perform a check across all immediate subgroups when clicking a header group to find **any** expanded group to determine if collapsing should be performed instead of expanding. This allows for the World Quests window to now be …

Modified Recursive Expand/Collapse Logic

---

.contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Darkshore/0 - Metadata.lua
.contrib/Parser/DATAS/02 - Outdoor Zones/10 Kul Tiras/01 Boralus/War Effort.lua
.contrib/Parser/DATAS/02 - Outdoor Zones/11 Zandalar/01 Dazar'alor/War Effort.lua
.contrib/Parser/DATAS/06 - Expansion Features/07 War Effort/Arathi Highlands Warfront/0 - Metadata.lua
.contrib/Parser/DATAS/06 - Expansion Features/07 War Effort/Arathi Highlands/0 - Metadata.lua
.contrib/Parser/DATAS/06 - Expansion Features/07 War Effort/Darkshore Warfront/0 - Metadata.lua
.contrib/Parser/DATAS/06 - Expansion Features/07 War Effort/Darkshore/0 - Metadata.lua
.contrib/Parser/DATAS/06 - Expansion Features/07 War Effort/Darkshore/Rares.lua

Fixed up some Warfront stuff to be consistent with the common database design.
Moved common information into proper metadata files for Darkshore warfront and 'new' Darkshore.
Removed random achievement tagging of some of the Warfront headers... it really doesn't make sense to tag non-collectible headers with achievement tooltips, especially when the header contains content completely unrelated to the achievement. Plus it makes the header itself show a 'Contains' based on the Achievement rather than the actual content of the header.
Also added the proper Darkshore Warfront MapID's to new metadata files so _hopefully_ this will finally work properly in ATT.
This should fix #518 for both Horde and Alliance players. Will have to verify for certain when it becomes available again for both …

Warfront Clean Up

---

AllTheThings.lua

Added a tweak to the /attwq window such that only things which are actually 'time-limited' are shown in normal refreshes of the window. Using an ALT-Click will cause additional Things to be shown which may be available to collect or complete at the current time, but not specifically be indicated as 'time-limited' by the API or database information. For instance, Heroic Deeds is _always_ available, so it will only be shown when using ALT-Click.
Similarly, showing available Quest Chains when Quest tracking is on will only show when ALT-Click is used.
Hopefully this should assuage those who are concerned that the /attwq list is too bloated with all the Things that can show when low on collection counts.

ATT - WQ Tweak for Time-Limited Things

---

AllTheThings.lua
locales/enUS.lua

Many, many, many people have asked for the ability to lock an ATT window in place, so I figured to give it a shot.
Basically, this allows for _any_ ATT window to be locked, and certain common windows to persist their Lock state between game sessions. In this way, each character can still define the position for each persisted window while maintaining the lock state account-wide.
We only have a _ton_ of hot-key/click combinations in use, but **Alt-Click on a Header** has not been used. It can easily be changed to another click combination if it makes more sense.

Added Window Locking

---

AllTheThings.lua

Since people complain both directions that "It isn't my fault" I decided to look at the code for both addons and make the simplest fix I could which achieves the following:
* Not removing information provided by either addon
* Not re-structuring the way tooltips are built from ATT
* Not looking for external data from one addon to the other to perform logic to fix the issue
Basically, using **UpdateTooltip** allows the game itself to refresh the tooltip as needed, and ArkInventory's code will ignore refreshing tooltips where the GameTooltip frame has this defined, or the Owner of said GameTooltip has this defined.

Fixed Tooltip Interaction with ArkInventory

---

.contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/1 - Stormwind City/Vendors.lua

The vendors in Orgrimmar stayed where they were, but the Stormwind ones moved. (See [wowhead comments](https://www.wowhead.com/npc=44246/magatha-silverton#comments:id=3238797)).
[Faldren Tillsdale the "Valor Quartermaster"](https://www.wowhead.com/npc=44245/faldren-tillsdale#comments) is currently MIA.

Update coords for Cataclysm vendors in Stormwind

---

.contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/1 - Stormwind City/Vendors.lua

The LFR/Normal/Heroic items are now correctly paired with their respective token.
Observed in-game with the Heroic token, while I already own the Heroic item:

Fix cost of Blackfang Battleweave Spaulders

---

.contrib/Parser/DATAS/02 - Outdoor Zones/03 Outland/Hellfire Peninsula.lua

As reported by Shoogen: https://us.forums.blizzard.com/en/blizzard/en/blizzard/t/incorrect-and-incomplete-data-in-wow-quest-apis/11112/3

Hellfire Peninsula quests removed in 9.0

---

AllTheThings.lua
src/base.lua

Not much as far as 'changes' but mostly re-alignment of code structures to better handle memory management of used variables.
Many variables were able to be localized and removed from being attached to the AllTheThings global table.
Additionally, there were various performance improvements due to reduced table key lookups and cost logic being re-implemented further.
Tooltip collection text is actually generated properly for tooltips which are not generated by an ATT window.

Logic realignment

---

.contrib/Parser/DATAS/02 - Outdoor Zones/13 Shadowlands/Zereth Mortis/Protoform Synthesis.lua

The fierce scarabid costs 400 Genesis Mote, as can be seen ingame and here: https://www.wowhead.com/spell=364665/fierce-scarabid

Use correct cost for fierce scarabid

---

AllTheThings.lua
src/base.lua

Mainly a huge refactor to basic Quest API querying and reward population within the ATT World Quests window. This should be far more accurate and smooth for pulling in currently-available content into the window.
There is still the known "issue" that 'storylines' are delayed and not currently accounted for depending on what data has been fully loaded on the Client. Hopefully I'll find a way to incorporate those rewards as well similar to the other updates...

Quest Population Updates

---

.contrib/Parser/DATAS/02 - Outdoor Zones/13 Shadowlands/Zereth Mortis/Protoform Synthesis.lua

The correct amount is 400 as can be seen in game and here: https://www.wowhead.com/spell=364695/terror-jelly

Fix Terror Jelly Genesis Mote amount

---

Settings.lua

I think this issue is caused by micro holidays/events ending, when it loops over the events it they will be nil and then settings wont be loaded

Settings keep resetting since new patch/new update fix

---

.contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/2 - Orgrimmar.lua

The new lines have a forward slash instead of a backslash, which doesn't visualize them correctly.

Fix Stone Guard Zarg description

---

.contrib/Parser/DATAS/06 - Expansion Features/06 Legion/Silithus (The Wound).lua

Source quest is no longer in game in retail, added conditional to prevent inaccurate quest flag. Attempt 2.

Quest 50046 Conditional Added

---

.contrib/Parser/DATAS/02 - Outdoor Zones/03 Outland/Shadowmoon Valley.lua

Should be [Akama](https://www.wowhead.com/npc=21700/akama) and not [Researcher Tiorus](https://www.wowhead.com/npc=21770). See: https://www.wowhead.com/quest=10707

Fix quest giver for The Ata'mal Terrace

---

.contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/Redridge Mountains.lua

Fixing typo in redridge descriptions for 'completeted' to 'completed'.

---

.contrib/Parser/DATAS/07 - Events/Remix Mists of Pandaria/Outdoor Zones/Townlong Steppes.lua

Ironwood Shield does not drop in Townlong Steppes. I have done a lot of farming, it didn't drop and Wowhead dropped by list and comments suggests the same thing: https://www.wowhead.com/item=216533/ironwood-shield#dropped-by

Update Townlong Steppes.lua

---

.contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Desolace.lua

Urga: Removed item rewards from the quest "Gizelton Caravan" as they are no longer available.

Urga: Removed item rewards from the quest "Gizelton Caravan" as they are no longer available.

---

locales/Default Locale.lua
src/Classes/Item.Classic.lua
src/Settings/Classic Settings.lua
src/Settings/Pages/General.lua

Add a new option to allow users to ignore white/grey items Appearances.
Tested on minilist and main panel.

Add trash items (white/grey) filtering in Classic

---

.contrib/Parser/DATAS/07 - Events/Expansion PreLaunch Events/09 Dragonflight.lua

- Adds the missing quest provider for baine and mayla
- Add missing sourceQuests for horde
- Re-order quests to have a neater appearance 
I'm new to AttTheThings contributing so I'm not 100% sure if providers or qp is the right attribute to use in this case. Also the source quests I added are needed before these mobs will appear, so I believe this is the correct spot for them.
Also completion of "65443 To the Dragon Isles!" makes these quests unobtainable. not sure if that has a place here or not. quest link: https://www.wowhead.com/quest=65444/to-the-dragon-isles

Add missing attributes for DF pre-launch

---

.contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Gorgrond.lua

Entrance will show up on the map when you ALT+Right Click on the entry.

Zone: Gorgrond - Found a better way to mark the cave entrances.

---

AllTheThings.toc
locales/cn.lua
locales/tw.lua

Separate zhCN and zhTW file.
The translation of zhTW is about 95% complete.

Localization: Separate zhCN and zhTW translation

---

.contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/1 - Darnassus.lua

coords are about 40m off
unsure if pre-cata coords are correct, only noticed for retail

update location of vinasia (npc id 4175)

---

.contrib/Parser/DATAS/11 - Character/New Character.lua

probably missing a few, was just going through my NC tab and looking up some entries that i didn't have :)

Adding descriptions to various New Character weapon entries

---

.contrib/Parser/DATAS/08 - PvP/03 Wrath of the Lich King PvP Seasons.lua

tested on cata classic
on retail, items are not flagged correctly because they were added in 7.x into the weapon arsenal, I suppose some specific flag should be added

[Cata] tag wotlk S5 honor weapons as never available

---

.contrib/Parser/DATAS/01 - Dungeons Raids/03 - Wrath of the Lich King/2 Naxxramas.lua

3 items have been lost with H+ wotlk (not added in dungeons, and naxx10 looting naxx25 stuff) :
Saltarello Shoes
Tunic of the Lost Pack
Gauntlets of Combined Strength
see https://www.wowhead.com/wotlk/guide/dungeons/titan-rune-dungeon-loot#unaccounted-for-items-in-defense-protocol

[Cata] mark naxx10 items lost with wotlk H+ as not available

---

.contrib/Parser/DATAS/01 - Dungeons Raids/03 - Wrath of the Lich King/Azjol-Nerub.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/03 - Wrath of the Lich King/Halls of Stone.lua

Quarry Chisel : not added in cata (surely 7.x)
Fungi-Coated Boots & Tangled Web Bindings : not added in cata (surely in 8.x)

[Cata] fix missing items from wotlk dungeons

---

.contrib/Parser/DATAS/21 - Holidays/Day of the Dead.lua

let's consider 8.x for white items
this one is temporary "Requires Day of the Dead"

[Cata] tag day of the dead mask as not collectible

---

.contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/Wetlands.lua

- "Incendicite Ore" (item 3340) has been made obsolete as of Cata. New one does not require a Profession to be acquired;
- "Black Whelp Scale" (item 7286) was relevant pre-Cata as it is part of (at least) 2 Classic Leatherworking Patterns;
- "Guardsman Belt" (item 3429) was added to vendors at 10.1.7;
- Remove a note on "Cursed Eye of Paleth" (item 2944) as it is permanently unlocked;
- Add proper Timelines on "Razormaw Hatchling" (item 48124) as it was a drop from a creature at one point;
- Move "Razormaw Matriarch's Nest" (object 202083) to Treasures.

EK/Wetlands: Refactor code to eliminate duplicate keys

---

.contrib/Parser/DATAS/02 - Outdoor Zones/03 Outland/Hellfire Peninsula.lua

The NPC [Jezebel Bican](https://www.wowhead.com/cata/npc=30734/jezebel-bican) is incorrectly marked to be in Dalaran. This should be Hellfire Peninsula instead.

[Cata/Retail] Properly mark Jezebel Bican's location as HFP, instead of Dalaran

---

.contrib/Parser/DATAS/02 - Outdoor Zones/04 Northrend/Wintergrasp.lua

Two fixes added for Cata Classic:
1. Jewelry has not been removed from Wintergrasp vendors 
2. The vendors for Wintergrasp PVP shoulders are still the old ones, unsure when these actually get moved - I've never played retail 🤷 
_Only tested on Alliance side_
**Validation required**
1. Confirm jewelry is also still present on Horde vendor
2. Confirm shoulders are also still on the same Horde vendor

[Cata Classic] Wintergrasp item fixes for Cata Classic

---

src/Modules/Contributor.lua

As a small map this constantly causes a report. This precision was calculated using the comment above this function

Add MapPrecisionOverrides for Chamber of Heart

---

.contrib/Parser/DATAS/01 - Dungeons Raids/01 - Classic/0.9 World Bosses.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/01 - Classic/1.6 Blackwing Lair.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/01 - Classic/1.7 Zul'Gurub.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/01 - Classic/2.5 Ruins of Ahn'Qiraj.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/01 - Classic/2.6 Temple of Ahn'Qiraj.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/01 - Classic/3.0 Naxxramas.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/01 - Classic/Dire Maul.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/02 - Burning Crusade/7 The Black Temple.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/02 - Burning Crusade/8 Sunwell Plateau.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/07 - Legion/1 - Raids/2 Trial of Valor.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/07 - Legion/1 - Raids/3 The Nighthold.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/07 - Legion/1 - Raids/4 Tomb of Sargeras.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/07 - Legion/1 - Raids/5 Antorus.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/07 - Legion/1 - Raids/6 Invasion Points.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/07 - Legion/2 - Dungeons/Cathedral of Eternal Night.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/07 - Legion/2 - Dungeons/Return to Karazhan.lua
.contrib/Parser/DATAS/01 - Dungeons Raids/07 - Legion/2 - Dungeons/Seat of the Triumvirate.lua

Classic:
Maraudon
World Bosses
Blackwing Lair
Zul'Gurub
Ruins of Ahn'Qiraj
Temple of Ahn'Qiraj
Naxxramas
TBC:
The Black temple
Sunwell plateau
Legion:
Invasion points
Trial of Valor
The Nighthold
Tomb of Sargeras
Antorus
Return of Karazhan
Seat of the triumvirate
Cathedral of Eternal Night

Fixed timeline in dungeons/raids added in a patch to fix wrong data in tooltips

---

.contrib/Parser/DATAS/01 - Dungeons Raids/07 - Legion/2 - Dungeons/Seat of the Triumvirate.lua

Just now the boss only have the correct id in the quest part of the file but in the loot part is using wrong id

Fix the ID of Viceroy Nezhar in hero and mythic

---

.contrib/Parser/DATAS/01 - Dungeons Raids/05 - Mists of Pandaria/5 - Throne of Thunder.lua

Fixes the minilist of LFR of ToT where megaera is missing in the common drops part
Removed redundant comment on LFR and Normal because ra den does not exist on those difficulties

2 ToT fixes
