ATTWoWAddon/AllTheThings

contrib/Parser/DATAS/2 - Zones/1 Kalimdor/Durotar & Echo Isles & Valley Of Trials.lua
Added a few missing quests, removed some quests that are no longer in the game, and added sourcequests/breadcrumbquestids where appropriate.
=> Fixed Valley of Trials and Echo Isles quests

contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Winterspring/Vendors.lua
Engineering vendor who doesn't appear to be listed, but is the only source for some schematics.
=> Adding Xizzer Fizzbolt in Winterspring

.gitignore
These shouldn't be committed to the repo.
=> .gitignore all desktop.ini files

.gitignore, contrib/Parser/DATAS/02 - Outdoor Zones/05 Pandaria/The Veiled Stair.lua
This pull request is a test to ensure I have the process down right. I've updated the coords for a single vendor (Blacktalon Quartermaster) and created the associated pull request.
I have the coords for most rares in Pandaria mapped out already. If the change I've made looks good, I can start updating them zone by zone and creating pull requests for each so you can review them.
=> Testing update for Pandaria locations

AllTheThings.toc, locales/zhCN.lua
Update zhCN.lua
Add zhCN.lua to the TOC file
=> Update zhCN.lua and TOC file

contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/Dun Morogh/1 - New Tinkertown/Quests.lua
We lost gnome restrictions in The Future of Gnomeregan here https://github.com/DFortun81/AllTheThings/commit/92573a6e07e4f8f570461d4d4a002c097fbcce3b ┗|｀O′|┛
=> some race restrictions were lost

contrib/Parser/DATAS/02 - Outdoor Zones/11 Zandalar/01 Dazar'alor/Quests.lua, contrib/Parser/DATAS/02 - Outdoor Zones/11 Zandalar/04 Zuldazar/Quests.lua
Mentioned 1 of these in the Discord error channel & in an open issue, hope this addition is worth something :-)
=> Added the first quests for the achievement 'Spirits Be With You'.

contrib/Parser/DATAS/02 - Outdoor Zones/08 Broken Isles/Broken Shore/Quests.lua
To create the Tailoring item 'Celumbra, the Night's Dichotomy'.
=> Added the Tailoring quest to get Legendary Legion mats (Shadowcloth & Starweave)

contrib/Parser/DATAS/02 - Outdoor Zones/08 Broken Isles/1 - Dalaran/Quests.lua, contrib/Parser/DATAS/02 - Outdoor Zones/08 Broken Isles/Suramar/Quests.lua, contrib/Parser/DATAS/02 - Outdoor Zones/10 Kul Tiras/04 Tiragarde Sound/World Quests.lua, contrib/Parser/DATAS/16 - Toys/Drop.lua, contrib/Parser/DATAS/16 - Toys/Quest.lua
#error: Missing quest reported by Gromwind.
=> Completed quest chain for toy 'Memory Cube' + activated WQ mentioned in #error

.contrib/Parser/DATAS/01 - Dungeons Raids/1 - Classic/2 - Dungeons/Blackrock Depths.lua, .contrib/Parser/DATAS/01 - Dungeons Raids/1 - Classic/2 - Dungeons/Lower Blackrock Spire.lua, .contrib/Parser/DATAS/01 - Dungeons Raids/1 - Classic/2 - Dungeons/Upper Blackrock Spire - Original.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/Burning Steppes/Quests.lua
- 4324 --  Yuka Screwspigot
- 4907 -- Tinkee Steamboil
- 4941 -- Eitrigg's Wisdom
=> Adding some legacy quests for issue #398

.contrib/Parser/DATAS/02 - Outdoor Zones/10 Kul Tiras/02 Drustvar/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/11 Zandalar/03 Vol'dun/Quests.lua, .contrib/Parser/DATAS/07 - Events/Darkmoon Faire/Vendors.lua, .contrib/Parser/DATAS/17 - NYI/Hidden Quest Triggers.lua
=> Some helpfull additions

.contrib/Parser/DATAS/02 - Outdoor Zones/04 Northrend/1 - Dalaran (Northrend)/01 - Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/09 Argus/Antoran Wastes/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/09 Argus/Krokuun/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/09 Argus/Mac'Aree/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/09 Argus/Vindicaar.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/10 Kul Tiras/01 Boralus/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/11 Zandalar/01 Dazar'alor/Quests.lua, .contrib/Parser/DATAS/06 - Expansion Features/06 Legion Class Halls/Acherus (Death Knight).lua, .contrib/Parser/DATAS/06 - Expansion Features/06 Legion Class Halls/Dreadscar Rift (Warlock).lua, .contrib/Parser/DATAS/06 - Expansion Features/06 Legion Class Halls/Hall Of The Guardian (Mage).lua, .contrib/Parser/DATAS/06 - Expansion Features/06 Legion Class Halls/Mardum The Shattered Abyss (Demon Hunter).lua, .contrib/Parser/DATAS/06 - Expansion Features/06 Legion Class Halls/Netherlight Temple (Priest).lua, .contrib/Parser/DATAS/06 - Expansion Features/06 Legion Class Halls/Sanctum Of Light (Paladin).lua, .contrib/Parser/DATAS/06 - Expansion Features/06 Legion Class Halls/Skyhold (Warrior).lua, .contrib/Parser/DATAS/06 - Expansion Features/06 Legion Class Halls/The Dreamgrove (Druid).lua, .contrib/Parser/DATAS/06 - Expansion Features/06 Legion Class Halls/The Hall Of Shadows (Rogue).lua, .contrib/Parser/DATAS/06 - Expansion Features/06 Legion Class Halls/The Heart Of Azeroth (Shaman).lua, .contrib/Parser/DATAS/06 - Expansion Features/06 Legion Class Halls/The Wandering Isle (Monk).lua, .contrib/Parser/DATAS/06 - Expansion Features/06 Legion Class Halls/Trueshot Lodge (Hunter).lua, .contrib/Parser/DATAS/17 - NYI/Hidden Quest Triggers.lua
Also some cleanup of todo's.
Quest 46940 was acceptable by any class in their Legion Class hall.
=> Adding more quests for issue #398

.contrib/Parser/DATAS/06 - Expansion Features/04 Draenor Garrison/Frostwall/Buildings/Stables.lua, .contrib/Parser/DATAS/06 - Expansion Features/04 Draenor Garrison/Lunarfall/Buildings/Stables.lua
PR for **sourceQuest** tags of chained Garrison Stables Quests
=> Garrison Stables Source Quests

AllTheThings.lua
No where in the addon currently are loot specs being utilized outside of the currently logged in character. This being the case, I've consolidated the loot spec retrieval into one method such that all items with loot spec tags will retrieve and indicate their corresponding specs in the same manner.
Additionally, rings/necks from Legion/BFA which return no spec information are technically lootable by any spec. Thus I've added this logic into the spec information so that drop chances can properly account for these items when determining drop chances.
As for the drop chance % information, I revised the logic and calculations a bit to try and accurately represent the information desired by these tooltip lines.
=> Loot Spec Adjustments

AllTheThings.lua
This can perhaps use more refinement or implementation, but currently as it stands I've added automatic acquisition of Storylines as provided by the API for all Zones into the World Quests window when Quest tracking or Debug mode is enabled. This allows seeing all world locations which currently would show a '!' on the respective map indicating an available Quest.
Further logic can be incorporated as well too, such as automatically applying coordinates for each Quest, or utilizing the Storyline information in a Quest popout list to show all Quests in a given Storyline (if supported by the API), but that can be discussed or added later.
Additionally, a LOT of the Quest object population logic for the World Quest Rebuild was duplicated, and I've consolidated that into its own function. I'm …
=> Storylines Feature

AllTheThings.lua
Noticed in the previous PR that some World Quest functionality was slightly different than normal due to some changes, so tried to fix them up to ensure that the user experience is not changed drastically.
=> Fixed some World Quest stuff

.contrib/Parser/DATAS/02 - Outdoor Zones/08 Broken Isles/2 - Quest Chains.lua
A while back I added some more information to various Balance of Power quests, and since I haven't gotten back to do more of it recently, I figured I should get it pushed up before someone else decides to spend time doing what I've already done :)
=> Legion: Balance of Power Updates

.contrib/Parser/DATAS/02 - Outdoor Zones/13 Shadowlands/The Maw/Rares.lua
Update Maw rare locations and descriptions with data from wowhead
=> Update Maw rares

.contrib/Parser/DATAS/01 - Dungeons Raids/1 - Classic/2 - Dungeons/Dire Maul.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/02 Orgrimmar/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Azshara/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Felwood/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Silithus/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Stonetalon Mountains/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Tanaris/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/Eastern Plaguelands/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/The Cape of Stranglethorn/Quests.lua, .contrib/Parser/DATAS/09 - PvP/Specific Battlegrounds/Arathi Basin.lua
Uh oh, I should have pushed to the PR in the fork instead of creating new branch, idk how it happened :D
Closes #689
=> Added some legacy quests for #398

AllTheThings.lua, Settings.lua, locales/enUS.lua
=> Screenshot options

.contrib/Parser/DATAS/01 - Dungeons Raids/2 - Burning Crusade/7 The Black Temple.lua, .contrib/Parser/DATAS/01 - Dungeons Raids/3 - Wrath of the Lich King/2 - Dungeons/Halls of Stone.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Azuremyst Isle/1 - Ammen Vale.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Teldrassil/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Winterspring/Factions.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/1 - Stormwind City/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/Isle of Quel'Danas/Vendors.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/The Scarlet Enclave/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/Tirisfal Glades/Artifacts.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/04 Northrend/1 - Dalaran (Northrend)/01 - Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/05 Pandaria/Kun-Lai Summit/Achievements.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Gorgrond/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/08 Broken Isles/1 - Dalaran/Flight Paths.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/08 Broken Isles/Highmountain/Flight Paths.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/08 Broken Isles/Suramar/Professions.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/08 Broken Isles/Suramar/Special.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/09 Argus/Antoran Wastes/Battle Pet.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/09 Argus/Krokuun/Battle Pet.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/09 Argus/Mac'Aree/Battle Pet.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/10 Kul Tiras/03 Stormsong Valley/Achievements.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/10 Kul Tiras/03 Stormsong Valley/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/10 Kul Tiras/03 Stormsong Valley/Zone Drops.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/11 Zandalar/03 Vol'dun/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/11 Zandalar/04 Zuldazar/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/11 Zandalar/04 Zuldazar/Vendors.lua, .contrib/Parser/DATAS/06 - Expansion Features/06 Legion Class Halls/Trueshot Lodge (Hunter).lua
Added mapIDs to coord
Fixes #783
=> Fixing invalid coordinates

.contrib/Parser/DATAS/06 - Expansion Features/08 Shadowlands/01 Covenants/02 Covenant Sanctum.lua
=> Add Stone-Etched Shawl 185854 to Adventures drops

locales/ruRU.lua
Missing objects locale, mini-holidays.
Also, is New Years Celebration even used anywhere? The only thing I can think of is two quests that appear only during 31st of December(id 8860 and 8861) but they are under Winter Veil category anyway.
=> ru_localization

.contrib/Parser/DATAS/06 - Expansion Features/05 Warlords of Draenor/Draenor Garrison/Common/Buildings/Fishing Shack.lua, .contrib/Parser/DATAS/06 - Expansion Features/08 Shadowlands/01 Covenants/Covenant - Kyrian/Sanctum Upgrades/Path of Ascension.lua, .contrib/Parser/DATAS/06 - Expansion Features/08 Shadowlands/01 Covenants/Covenant - Venthyr/Sanctum Upgrades/The Ember Court.lua
Savage Fishing Pole is missing from Fishing Shack
Ember Court HQTs
Path of Ascension HQTs
=> Some of my reports from #retail-errors

.contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Darkshore/Quests.lua
Timely Arrival: added coörds
A Love Eternal: "Need to finish A Cure In The Dark" too
=> Some Darkshore fixes

.contrib/Parser/DATAS/05 - Achievements/03 - Exploration/09 - Legion.lua
I followed the format of the shadowlands achievement, I added in all of the CRS #s and coords for the legion version of the achievement. Feel free to decline if I did something wrong with it, I have been talking to Runawaynow on discord about this. If you do decline this can you let me know why and what I did wrong so I can fix it, If everything is right, I can have the remainder of these Achievements fixed by this time next week
=> Update 09 - Legion.lua

.contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Frostfire Ridge/Achievements.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Gorgrond/Achievements.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Nagrand/Achievements.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Shadowmoon Valley/Achievements.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Spires of Arak/Achievements.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Talador/Achievements.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Tanaan Jungle/Achievements.lua, .contrib/Parser/DATAS/05 - Achievements/03 - Exploration/08 - Draenor.lua
This is the Draenor section of the squirrels achieves. 
If you have any questions, comment for concerns let me know please. 
Ill get the rest done when i can.
=> To All The Squirrels Through Time and Space

.contrib/Parser/DATAS/02 - Outdoor Zones/10 Kul Tiras/02 Drustvar/Achievements.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/10 Kul Tiras/03 Stormsong Valley/Achievements.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/10 Kul Tiras/04 Tiragarde Sound/Achievements.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/11 Zandalar/01 Dazar'alor/Achievements.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/11 Zandalar/02 Nazmir/Achievements.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/11 Zandalar/03 Vol'dun/Achievements.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/11 Zandalar/04 Zuldazar/Achievements.lua, .contrib/Parser/DATAS/05 - Achievements/03 - Exploration/10 - Battle for Azeroth.lua
BFA Squirrels' achievement moved from Zone files to Achievement/exploration file.
Tracking added.
=> To All the Squirrels I Set Sail to See adjustments

.contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Gorgrond/Achievements.lua, .contrib/Parser/DATAS/05 - Achievements/03 - Exploration/08 - Draenor.lua
Added tracking
Moved from Outdoors to Achieve/Explore
=> Gorgrond Monster Hunter Adjustments

.contrib/Parser/DATAS/02 - Outdoor Zones/08 Broken Isles/Professions.lua
Fix from my #retail-errors thread https://discord.com/channels/242423099184775169/970618281092333598
=> Legion leatherworking quest requirements

.contrib/Parser/DATAS/01 - Dungeons Raids/1 - Classic/Blackrock Depths.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/01 Darnassus/Professions.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/02 Orgrimmar/Professions.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/04 Thunder Bluff/Professions.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/1 - Ironforge.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/1 - Stormwind City.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/1 - Undercity.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/11 Zandalar/02 Nazmir/Treasures.lua, .contrib/Parser/DATAS/03 - World Drops/02 Pickpocketing/Pickpocketing.lua, .contrib/Parser/DATAS/03 - World Drops/03 Classic/07 Pets.lua, .contrib/Parser/DATAS/03 - World Drops/04 Burning Crusade/03 Weapons.lua, .contrib/Parser/DATAS/03 - World Drops/05 Wrath of the Lich King/07 Miscellaneous.lua, .contrib/Parser/DATAS/03 - World Drops/06 Cataclysm/03 Weapons.lua, .contrib/Parser/DATAS/06 - Expansion Features/05 Warlords of Draenor/Draenor Garrison/Common/Buildings/Fishing Shack.lua
Not sure if I handled world drop things correctly, but I tried.
=> Keeper ta'hult grey items sources and descriptions

.contrib/Parser/DATAS/02 - Outdoor Zones/13 Shadowlands/Zereth Mortis/Achievements.lua
Added coords to Traversing the Spheres
=> Traversing the Spheres

.contrib/Harvesters/WoWTools Harvester/Harvester.py
@gbrage, it's still WIP but you can take a look and tell me what needs changing.
Related to #1022
=> Harvester edits

Settings.lua, locales/enUS.lua
Added 'Cmd' Modifier for Mac environments
Cleaned up some Settings logic for Tooltip Modifier key toggles
Fixes #1131
=> Issue #1131

src/Modules/Events.lua
Minor Event Module performance tweaks
=> Event module tweaks

src/base.lua
local GetAddOnMetadata = GetAddOnMetadata or C_AddOns.GetAddOnMetadata
=> Update depreciated function usage.

.contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Durotar.lua
=> Exclude Evoker from Echo Isles quests

.contrib/Parser/DATAS/10 - Professions/Alchemy.lua, .contrib/Parser/DATAS/10 - Professions/Blacksmithing.lua, .contrib/Parser/DATAS/10 - Professions/Engineering.lua, .contrib/Parser/DATAS/10 - Professions/Herbalism.lua, .contrib/Parser/DATAS/10 - Professions/Inscription.lua, .contrib/Parser/DATAS/10 - Professions/Jewelcrafting.lua, .contrib/Parser/DATAS/10 - Professions/Tailoring.lua
Fixes https://github.com/DFortun81/AllTheThings/issues/1583.
=> DF: Intro profession quests are mutually exclusive

locales/pt.lua
Updates general and interface settings tab and couple parts of the big chunk
=> Updates locale to translate to PT-BR client

.contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Ashenvale.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Azshara.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Darkshore.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Desolace.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Durotar.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Dustwallow Marsh.lua
Massimporting standard quest objectives (loot item and kills) for Kalimdor zones.
ATM still a draft, but i want to give some time to review already
=> Massimport objective data for Kalimdor zones

.contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Felwood.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Feralas.lua
Massimport objective data for Fellwood and Feralas
=> Massimport objective data for Fellwood and Feralas

.contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/Mount Hyjal.lua
Massimport quest data for Mount Hyjal
Draft, because more stuff to be added
=> Massimport quest data for Mount Hyjal

.contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Gorgrond.lua
Expand some descriptions for treasures.
I don't know if this can be done in some other way.
=> Zone: Gorgrond - Update Descriptions for easier access to some treasures

.contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Frostfire Ridge.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Gorgrond.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Nagrand.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Shadowmoon Valley.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Spires of Arak.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Talador.lua
Frostfire Ridge: Additional spawn points for Gorok from WoWhead
Spires of Arak: Offering to the Raven Mother coordinates from personal observation. Old one was off by a bit
Talador: Additional updates to Descriptions, coordinates and comments. Spawn locations for Teroclaw nests taken in-game. There are more of them throughout the area but I figured these are more than enough
=> Zone/Draenor: More updates to coordinates and descriptions

.contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/Talador.lua
and enable quest related NPCs to have the note in their tooltip
=> Zone/Draenor-Talador: Update description for quest Frenzied Manafeeders

.contrib/Parser/DATAS/02 - Outdoor Zones/15 Khaz Algar/Isle of Dorn/Quests.lua
Source: https://www.wowhead.com/quest=82801/beetlejeweled
=> TWW/Isle of Dorn: Update rewards for quest Beetlejeweled (82801)

.contrib/Parser/DATAS/02 - Outdoor Zones/15 Khaz Algar/Isle of Dorn/Quests.lua, .contrib/Parser/DATAS/17 - NYI/Unsorted.lua
=> TWW/Isle of Dorn: Quest Reward for Best Friends, Same Ends (83181)

.contrib/Parser/DATAS/16 - Delves/11 - The War Within/Delves.lua
https://www.wowhead.com/object=455524
=> TWW/Delves: Kriegval's Rest, Update object ID for the missing Sturdy Chest

AllTheThings_Cata.toc, AllTheThings_Vanilla.toc, AllTheThings_Wrath.toc
=> localization: add zhTW on no-retail TOC

classic/locales.lua
Try to fix DFortun81/AllTheThings#1789 again
=> [Localization] Fixes error in Classic

.contrib/Parser/DATAS/02 - Outdoor Zones/09 Argus/1 - Vindicaar.lua
Fix Location of Thaumaturge Vashreen
=> Update 1 - Vindicaar.lua

.contrib/Parser/DATAS/06 - Expansion Features/08 Shadowlands/01 Covenants/Covenant - Venthyr/Sanctum Upgrades/Transport Network.lua
Venthyr mirrors are now available every day, not once a week.
=> Update mirror, now is daily, not weekly

.contrib/Parser/DATAS/08 - PvP/World.lua, .contrib/Parser/DATAS/21 - Holidays/WoW Anniversary.lua
Updated some zhCN locale in .contrib/Parser.
=> Update zhCN locale.

.contrib/Parser/DATAS/02 - Outdoor Zones/13 Shadowlands/Maldraxxus/Treasure Chests.lua
Update description for Empty Nightcap Cask
=> Update Treasure Chests.lua

.contrib/Parser/DATAS/02 - Outdoor Zones/13 Shadowlands/Zereth Mortis/Cypher Of The First Ones.lua
i have over 30 in my inventory
=> ephemera strand not unique

.contrib/Parser/DATAS/08 - PvP/03 Wrath of the Lich King PvP Seasons.lua
revert the change done on wands
add hunter waraxe (with shared appearance)
=> [Cata] add wotlk S1 savage weapons still available

.contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/2 - Orgrimmar.lua
First PR to this repo, not sure how to check if it works.
=> Add Sergeant Thunderhorn to cata firelands phase as base pvp vendor

src/Classes/Transmog.lua
just added a conditional around the print statements
=> fix reporting of new items when report option unchecked

.contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/Elwynn Forest.lua
Eliminate warnings related to duplicate keys and adjust preprocessors accordingly
=> EK/Elwynn Forest: Refactor code to eliminate duplicate keys

.contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/Loch Modan.lua
- Vrok Blunderblast does not sell anything pre-Cata
=> EK/Loch Modan: Refactor code to eliminate duplicate keys

.contrib/Parser/DATAS/02 - Outdoor Zones/02 Eastern Kingdoms/Burning Steppes.lua
- "Merge" a couple of duplicate Zone Drops
=> EK/Burning Steppes: Refactor code to eliminate duplicate keys

.contrib/Parser/DATAS/02 - Outdoor Zones/01 Kalimdor/1 - Darnassus.lua
takes you to the middle of nowhere, im standing in the npcs location
=> updating location for Vaean (npc 4228)

.contrib/Parser/DATAS/21 - Holidays/Day of the Dead.lua, .contrib/Parser/DATAS/21 - Holidays/Love is in the Air.lua
Same workaround as Whimsical Skull Mask
=> [Cata] Lovely Charm Bracelet is not collectible before white items are added in legion

src/Settings/Classic Settings.lua, src/Settings/Retail Settings.lua, src/UI/World Map Button.lua
I tried installing the Krowi's World Map buttons lib directly but seems it just needs to be included via other addons which use that functionality, and I haven't had time to test that specifically.
=> [Logic] Add handling to utilize Krowi's WorldMap Button lib if it exists

.contrib/Parser/DATAS/02 - Outdoor Zones/15 Khaz Algar/Azj-Kahet/Zone Drops.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/15 Khaz Algar/Hallowfall/Zone Drops.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/15 Khaz Algar/Isle of Dorn/Zone Drops.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/15 Khaz Algar/The Ringing Deeps/Quests.lua, .contrib/Parser/DATAS/02 - Outdoor Zones/15 Khaz Algar/The Ringing Deeps/Zone Drops.lua
the quest have incorrect provider, and the item is unlisted
=> Fix quest Everyday I'm Snufflin'

.contrib/Parser/DATAS/02 - Outdoor Zones/15 Khaz Algar/Undermine/Rares.lua
these questids were swapped when they recently got fixed
=> fix undermine rare quests

.contrib/Parser/DATAS/02 - Outdoor Zones/07 Draenor/0 - Metadata.lua
fix the issues where battlepets showing added in patch 5.0.4 or achievements showing added in patch 3.0.2
=> Fix a lot of issues in all draenor zones due the lack of timeline in the continent

.contrib/Parser/DATAS/13 - Black Market Auction House/Black Market Auction House.lua
=> Madam Goya is in dalaran too and she is functional since TWW

.contrib/Parser/DATAS/01 - Dungeons Raids/03 - Wrath of the Lich King/9 The Ruby Sanctum.lua, .contrib/Parser/DATAS/01 - Dungeons Raids/03 - Wrath of the Lich King/Halls of Reflection.lua, .contrib/Parser/DATAS/01 - Dungeons Raids/03 - Wrath of the Lich King/Pit of Saron.lua, .contrib/Parser/DATAS/01 - Dungeons Raids/03 - Wrath of the Lich King/The Forge of Souls.lua, .contrib/Parser/DATAS/01 - Dungeons Raids/03 - Wrath of the Lich King/Trial of the Champion.lua
Trial of champion
Forge of Souls
Pit of Saron
Halls of reflection
Ruby sanctum
=> Added missing timeline in WTLK dungeons/raids to fix tooltips issues

.contrib/Parser/DATAS/00 - DB/Parser Setup Data/MAPID_MERGE_REPLACEMENTS.lua
Source: https://warcraft.wiki.gg/wiki/Warsong_Gulch
=> [Parser] Correct timeline of WSG map

.contrib/Parser/DATAS/01 - Dungeons Raids/07 - Legion/1 - Raids/2 Trial of Valor.lua
Additionally added some real timelines for removed things and sorted loot alphabetically.
Please check if this implementation is correct and I'll start converting other instances.
=> Rework Trial of Valor to use InstanceHelper
